[package]
name = "Orion"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.3"
image = "0.25.5"
iyes_perf_ui = "0.4.0"
rand = { version = "0.8", features = ["std"] }
winit = "0.30.9"

[dependencies.getrandom]
version = "0.2"
features = ["js"]
